### ISSUE TITLE
GameObjects should be sorted by subtype

### ISSUE THREAD

**Issue by HerrAndersson** [rikhardsvensson/StortSpel-Grupp1#77]
The GameObject vector used for rendering should be sorted based on subtype to minimize the number of context switches and enable usage of different textures on the same object type.

This can be done using operator< and std::sort()

**Comment by rikhardsvensson** [comment]
Correct me if I'm wrong but wouldn't this could create performance issues during sorting due to vectors essentially being arrays. We could consider changing _gameObjects to a std::vectorstd::list<GameObject*> container. Since all current usage of the subvectors is based on iteration we wont loose any performance with existing code. And as long as we keep the lists sorted at all times no single insert would cost more than O(n).

**Comment by Zache51** [comment]
It is now sorted by texture instead.
